[browser]
gatherUsageStats = false

[server]
runOnSave = true
maxUploadSize = 10
maxMessageSize = 10

[theme]
primaryColor="#F63366"
backgroundColor="#FCF2E5"
secondaryBackgroundColor="#F8E4C7"
textColor="#302730"
