[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[server]
runOnSave = true
port = 3000
maxUploadSize = 10
maxMessageSize = 10

[theme]
primaryColor="#F63366"
backgroundColor="#FCF2E5"
secondaryBackgroundColor="#F8E4C7"
textColor="#262730"
font="sans serif"
